name: om_scrollable_positioned_list
version: 0.3.8+9
description: >
  A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/omar0141/flutter_scrollable_positined_list
environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0-0
  flutter_test:
    sdk: flutter
